#!/bin/bash

# Jxion API - PostgreSQL Database Setup Script for Linux
# This script creates the database and user for local development

set -e

echo "🔧 Jxion API - PostgreSQL Setup"
echo "================================"
echo ""

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo "❌ PostgreSQL is not installed or not in PATH"
    echo "Please install PostgreSQL first:"
    echo "  Arch: sudo pacman -S postgresql"
    echo "  Ubuntu/Debian: sudo apt install postgresql"
    exit 1
fi

echo "✅ PostgreSQL found: $(psql --version)"
echo ""

# Check if PostgreSQL is running
if ! pg_isready &> /dev/null; then
    echo "⚠️  PostgreSQL is not running"
    echo "Please start PostgreSQL first:"
    echo "  sudo systemctl start postgresql"
    echo "  OR: sudo systemctl enable --now postgresql"
    exit 1
fi

echo "✅ PostgreSQL is running"
echo ""

# Default values
DB_NAME="jxion"
DB_USER="jxion"
DB_PASS="jxion_dev_password_$(openssl rand -hex 4)"

# Try to use postgres superuser to create database and user
echo "📝 Creating database and user..."

# Try with sudo first (most common on Linux)
if sudo -u postgres psql -c "SELECT 1" &>/dev/null; then
    echo "Using postgres superuser via sudo..."
    
    # Create user if it doesn't exist
    sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';" 2>/dev/null || \
        echo "User $DB_USER already exists or created"
    
    # Create database
    sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" 2>/dev/null || \
        echo "Database $DB_USER already exists or created"
    
    # Grant privileges
    sudo -u postgres psql -d $DB_NAME -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;" 2>/dev/null || true
    
elif psql -U postgres -c "SELECT 1" &>/dev/null; then
    echo "Using postgres superuser directly..."
    
    # Create user if it doesn't exist
    psql -U postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';" 2>/dev/null || \
        echo "User $DB_USER already exists or created"
    
    # Create database
    psql -U postgres -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" 2>/dev/null || \
        echo "Database $DB_NAME already exists or created"
    
    # Grant privileges
    psql -U postgres -d $DB_NAME -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;" 2>/dev/null || true
    
else
    echo "⚠️  Could not connect to PostgreSQL as postgres user"
    echo "Please run this script with appropriate permissions or manually create:"
    echo "  sudo -u postgres createuser $DB_USER"
    echo "  sudo -u postgres createdb -O $DB_USER $DB_NAME"
    exit 1
fi

echo ""
echo "✅ Database and user created successfully"
echo ""

# Build DATABASE_URL
DATABASE_URL="postgres://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}?sslmode=disable"

echo "🔗 Your DATABASE_URL:"
echo "$DATABASE_URL"
echo ""

# Create .env file
ENV_FILE="apps/jxion-api/.env"
echo "📝 Creating .env file at $ENV_FILE..."

# Create directory if it doesn't exist
mkdir -p "$(dirname "$ENV_FILE")"

# Write .env file
cat > "$ENV_FILE" << EOF
# Jxion API - Environment Variables
# Generated by setup-db.sh

# Database Configuration
DATABASE_URL=$DATABASE_URL

# Server Configuration
PORT=8080

# Redis Configuration (optional)
# REDIS_URL=redis://localhost:6379/0
EOF

echo "✅ Created .env file at $ENV_FILE"
echo ""
echo "🎉 Setup complete!"
echo ""
echo "Next steps:"
echo "1. Review the .env file: cat $ENV_FILE"
echo "2. Start the API server: cd apps/jxion-api && go run cmd/server/main.go"
echo "3. The server will automatically run migrations on startup"
echo ""

