/**
 * Jxion Stack — AI Component Generator
 * Phase Reference: Phase 4 — AI Assistant & Automation
 * Description: AI-powered component generator that converts components between frameworks
 *
 * This page allows:
 * - Converting React components to Svelte/Vue/etc
 * - Generating components from templates
 * - AI-assisted component creation
 * - Component metadata extraction
 */

import { useState, useEffect } from 'react';
import {
  Code,
  Sparkles,
  RefreshCw,
  Download,
  Copy,
  CheckCircle2,
  AlertCircle,
  FileCode,
  Zap,
} from 'lucide-react';
import {
  convertComponent,
  extractComponentMetadata,
  type SourceFramework,
  type TargetFramework,
  type ConversionResult,
} from '@jxion/core';

interface GeneratedComponent {
  code: string;
  framework: TargetFramework;
  metadata: ConversionResult['metadata'];
  timestamp: number;
}

export default function ComponentGenerator() {
  const [sourceCode, setSourceCode] = useState('');
  const [sourceFramework, setSourceFramework] =
    useState<SourceFramework>('react');
  const [targetFramework, setTargetFramework] =
    useState<TargetFramework>('svelte');
  const [componentName, setComponentName] = useState('Hero');
  const [generatedComponents, setGeneratedComponents] = useState<
    GeneratedComponent[]
  >([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiGenerating, setAiGenerating] = useState(false);

  // Example React component template
  const exampleReactComponent = `import React from 'react';
import styles from './Component.module.scss';

interface ComponentProps {
  title: string;
  subtitle?: string;
  description?: string;
  onAction?: () => void;
}

export const Component: React.FC<ComponentProps> = ({
  title,
  subtitle = "",
  description = "",
  onAction,
}) => {
  return (
    <section className={styles.component}>
      <h1 className={styles.title}>{title}</h1>
      {subtitle && <h2 className={styles.subtitle}>{subtitle}</h2>}
      {description && <p className={styles.description}>{description}</p>}
      {onAction && (
        <button className={styles.button} onClick={onAction}>
          Action
        </button>
      )}
    </section>
  );
};

export default Component;`;

  useEffect(() => {
    // Load example on mount
    if (!sourceCode) {
      setSourceCode(exampleReactComponent);
    }
  }, []);

  const handleConvert = async () => {
    if (!sourceCode.trim()) {
      setError('Please provide source code');
      return;
    }

    setLoading(true);
    setError(null);
    setSuccess(null);

    try {
      // Extract metadata first
      const metadata = extractComponentMetadata(sourceCode);
      const detectedName = metadata.componentName || componentName;

      // Convert component
      const result = convertComponent({
        sourceCode,
        sourceFramework,
        targetFramework,
        componentName: detectedName,
      });

      // Add to generated components
      const generated: GeneratedComponent = {
        code: result.code,
        framework: targetFramework,
        metadata: result.metadata,
        timestamp: Date.now(),
      };

      setGeneratedComponents((prev) => [generated, ...prev]);
      setSuccess(`Component converted to ${targetFramework} successfully!`);
      setTimeout(() => setSuccess(null), 5000);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Conversion failed');
    } finally {
      setLoading(false);
    }
  };

  const handleAIGenerate = async () => {
    if (!aiPrompt.trim()) {
      setError('Please provide a component description');
      return;
    }

    setAiGenerating(true);
    setError(null);
    setSuccess(null);

    try {
      // Call AI API (using free tier LLM)
      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3005';
      const response = await fetch(`${apiUrl}/api/ai/generate-component`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: aiPrompt,
          framework: sourceFramework,
          componentName,
        }),
      });

      if (!response.ok) {
        throw new Error('AI generation failed');
      }

      const data = await response.json();
      setSourceCode(data.code || data.component);
      setSuccess('Component generated by AI!');
      setTimeout(() => setSuccess(null), 5000);
    } catch (err) {
      // Fallback: Use template-based generation
      console.warn('AI API not available, using template fallback');
      const fallbackCode = generateFromTemplate(aiPrompt, sourceFramework);
      setSourceCode(fallbackCode);
      setSuccess('Component generated from template (AI API unavailable)');
      setTimeout(() => setSuccess(null), 5000);
    } finally {
      setAiGenerating(false);
    }
  };

  const generateFromTemplate = (
    prompt: string,
    framework: SourceFramework
  ): string => {
    // Simple template-based generation
    const lowerPrompt = prompt.toLowerCase();
    const hasButton =
      lowerPrompt.includes('button') || lowerPrompt.includes('cta');
    const hasImage =
      lowerPrompt.includes('image') || lowerPrompt.includes('photo');
    const hasList =
      lowerPrompt.includes('list') || lowerPrompt.includes('items');

    if (framework === 'react') {
      return `import React from 'react';
import styles from './Component.module.scss';

interface ComponentProps {
  title: string;
  ${hasButton ? 'onAction?: () => void;' : ''}
  ${hasImage ? 'imageUrl?: string;' : ''}
  ${hasList ? 'items?: string[];' : ''}
}

export const Component: React.FC<ComponentProps> = ({
  title,
  ${hasButton ? 'onAction,' : ''}
  ${hasImage ? 'imageUrl,' : ''}
  ${hasList ? 'items = [],' : ''}
}) => {
  return (
    <section className={styles.component}>
      <h1 className={styles.title}>{title}</h1>
      ${
        hasImage
          ? '<img src={imageUrl} alt={title} className={styles.image} />'
          : ''
      }
      ${
        hasList
          ? '<ul className={styles.list}>{items.map((item, i) => <li key={i}>{item}</li>)}</ul>'
          : ''
      }
      ${
        hasButton
          ? '<button className={styles.button} onClick={onAction}>Action</button>'
          : ''
      }
    </section>
  );
};

export default Component;`;
    }

    return `// Generated component for ${framework}`;
  };

  const handleCopy = (code: string) => {
    navigator.clipboard.writeText(code);
    setSuccess('Code copied to clipboard!');
    setTimeout(() => setSuccess(null), 3000);
  };

  const handleDownload = (
    code: string,
    framework: TargetFramework,
    name: string
  ) => {
    const extension =
      framework === 'svelte' ? 'svelte' : framework === 'vue' ? 'vue' : 'tsx';
    const filename = `${name}.${extension}`;
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-serif font-bold text-noir-black mb-2 flex items-center gap-3">
            <Sparkles className="text-noir-gold" size={32} />
            AI Component Generator
          </h1>
          <p className="text-noir-gray-600 font-sans">
            Convert components between frameworks or generate new ones with AI
            assistance
          </p>
        </div>
      </div>

      {/* Success/Error Messages */}
      {success && (
        <div className="p-4 bg-green-50 border border-green-200 rounded-lg flex items-center gap-3">
          <CheckCircle2 className="text-green-600" size={20} />
          <span className="text-green-800 font-sans font-semibold">
            {success}
          </span>
        </div>
      )}

      {error && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg flex items-center gap-3">
          <AlertCircle className="text-red-600" size={20} />
          <span className="text-red-800 font-sans font-semibold">{error}</span>
        </div>
      )}

      {/* AI Generation Section */}
      <div className="bg-gradient-to-br from-purple-50 to-blue-100 rounded-lg p-6 border border-purple-200">
        <h2 className="text-xl font-serif font-semibold text-noir-black mb-4 flex items-center gap-2">
          <Zap className="text-purple-600" size={24} />
          AI-Assisted Generation
        </h2>
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-sans font-semibold text-noir-gray-700 mb-2">
              Describe your component
            </label>
            <textarea
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
              placeholder="e.g., A hero section with title, subtitle, description, and a call-to-action button"
              className="w-full h-24 px-4 py-3 border border-noir-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-noir-gold focus:border-transparent font-sans text-sm"
            />
          </div>
          <div className="flex gap-4">
            <select
              value={sourceFramework}
              onChange={(e) =>
                setSourceFramework(e.target.value as SourceFramework)
              }
              className="px-4 py-2 border border-noir-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-noir-gold font-sans"
            >
              <option value="react">React</option>
              <option value="svelte">Svelte</option>
              <option value="vue">Vue</option>
            </select>
            <input
              type="text"
              value={componentName}
              onChange={(e) => setComponentName(e.target.value)}
              placeholder="Component Name"
              className="px-4 py-2 border border-noir-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-noir-gold font-sans"
            />
            <button
              onClick={handleAIGenerate}
              disabled={aiGenerating || !aiPrompt.trim()}
              className="flex items-center gap-2 px-6 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg font-sans font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {aiGenerating ? (
                <>
                  <RefreshCw size={18} className="animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles size={18} />
                  Generate with AI
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Conversion Section */}
      <div className="grid grid-cols-12 gap-6">
        {/* Source Code Editor */}
        <div className="col-span-6 bg-white rounded-lg shadow-md p-6 border border-noir-gray-200">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-serif font-semibold text-noir-black flex items-center gap-2">
              <FileCode size={20} />
              Source Code
            </h2>
            <select
              value={sourceFramework}
              onChange={(e) =>
                setSourceFramework(e.target.value as SourceFramework)
              }
              className="px-3 py-1 border border-noir-gray-300 rounded-lg text-sm font-sans"
            >
              <option value="react">React</option>
              <option value="svelte">Svelte</option>
              <option value="vue">Vue</option>
            </select>
          </div>
          <textarea
            value={sourceCode}
            onChange={(e) => setSourceCode(e.target.value)}
            className="w-full h-[600px] px-4 py-3 border border-noir-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-noir-gold focus:border-transparent font-mono text-sm"
            spellCheck={false}
          />
          <div className="mt-4 flex gap-2">
            <button
              onClick={handleConvert}
              disabled={loading || !sourceCode.trim()}
              className="flex items-center gap-2 px-4 py-2 bg-noir-gold hover:bg-[#FFC700] text-noir-black rounded-lg font-sans font-semibold transition-colors disabled:opacity-50"
            >
              {loading ? (
                <>
                  <RefreshCw size={18} className="animate-spin" />
                  Converting...
                </>
              ) : (
                <>
                  <Code size={18} />
                  Convert
                </>
              )}
            </button>
            <select
              value={targetFramework}
              onChange={(e) =>
                setTargetFramework(e.target.value as TargetFramework)
              }
              className="px-4 py-2 border border-noir-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-noir-gold font-sans"
            >
              <option value="svelte">Svelte</option>
              <option value="vue">Vue</option>
              <option value="react">React</option>
              <option value="solidjs">SolidJS</option>
            </select>
          </div>
        </div>

        {/* Generated Components */}
        <div className="col-span-6 bg-white rounded-lg shadow-md p-6 border border-noir-gray-200">
          <h2 className="text-xl font-serif font-semibold text-noir-black mb-4 flex items-center gap-2">
            <Code size={20} />
            Generated Components
          </h2>
          {generatedComponents.length === 0 ? (
            <div className="flex items-center justify-center h-[600px] text-noir-gray-500">
              <p className="font-sans">No components generated yet</p>
            </div>
          ) : (
            <div className="space-y-4 max-h-[600px] overflow-y-auto">
              {generatedComponents.map((comp, idx) => (
                <div
                  key={idx}
                  className="border border-noir-gray-200 rounded-lg p-4"
                >
                  <div className="flex items-center justify-between mb-2">
                    <div>
                      <span className="text-sm font-sans font-semibold text-noir-black">
                        {comp.metadata.componentName}
                      </span>
                      <span className="ml-2 text-xs text-noir-gray-500">
                        ({comp.framework})
                      </span>
                    </div>
                    <div className="flex gap-2">
                      <button
                        onClick={() => handleCopy(comp.code)}
                        className="p-1 hover:bg-noir-gray-100 rounded"
                        title="Copy"
                      >
                        <Copy size={16} />
                      </button>
                      <button
                        onClick={() =>
                          handleDownload(
                            comp.code,
                            comp.framework,
                            comp.metadata.componentName
                          )
                        }
                        className="p-1 hover:bg-noir-gray-100 rounded"
                        title="Download"
                      >
                        <Download size={16} />
                      </button>
                    </div>
                  </div>
                  <pre className="text-xs font-mono bg-noir-gray-50 p-2 rounded overflow-x-auto max-h-48">
                    {comp.code.substring(0, 500)}
                    {comp.code.length > 500 && '...'}
                  </pre>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Info Panel */}
      <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg p-6 border border-blue-200">
        <h3 className="text-lg font-serif font-semibold text-noir-black mb-3 flex items-center gap-2">
          <Code size={20} className="text-blue-600" />
          How It Works
        </h3>
        <ul className="space-y-2 text-sm text-noir-gray-700 font-sans">
          <li className="flex items-start gap-2">
            <span className="text-blue-600">•</span>
            <span>
              <strong>AI Generation:</strong> Describe your component and let AI
              generate the code
            </span>
          </li>
          <li className="flex items-start gap-2">
            <span className="text-blue-600">•</span>
            <span>
              <strong>Framework Conversion:</strong> Convert React components to
              Svelte, Vue, or other frameworks
            </span>
          </li>
          <li className="flex items-start gap-2">
            <span className="text-blue-600">•</span>
            <span>
              <strong>Component Registry:</strong> Generated components are
              compatible with the Jxion component registry
            </span>
          </li>
          <li className="flex items-start gap-2">
            <span className="text-blue-600">•</span>
            <span>
              <strong>Export & Use:</strong> Download or copy generated code to
              use in your project
            </span>
          </li>
        </ul>
      </div>
    </div>
  );
}
