/**
 * Jxion Stack — AI Component Generator
 * Phase Reference: Phase 4 — AI Assistant & Automation
 * Description: AI-powered component generator that converts components between frameworks
 *
 * This page allows:
 * - Converting React components to Svelte/Vue/etc
 * - Generating components from templates
 * - AI-assisted component creation
 * - Component metadata extraction
 */

import { useState, useEffect } from 'react';
import {
  Code,
  Sparkles,
  RefreshCw,
  Download,
  Copy,
  CheckCircle2,
  AlertCircle,
  FileCode,
  Zap,
} from 'lucide-react';
import {
  convertComponent,
  extractComponentMetadata,
  type SourceFramework,
  type TargetFramework,
  type ConversionResult,
} from '@jxion/core';
import scssStyles from './ComponentGenerator.module.scss';

interface GeneratedComponent {
  code: string;
  framework: TargetFramework;
  metadata: ConversionResult['metadata'];
  timestamp: number;
}

export default function ComponentGenerator() {
  const [sourceCode, setSourceCode] = useState('');
  const [sourceFramework, setSourceFramework] =
    useState<SourceFramework>('react');
  const [targetFramework, setTargetFramework] =
    useState<TargetFramework>('svelte');
  const [componentName, setComponentName] = useState('Hero');
  const [generatedComponents, setGeneratedComponents] = useState<
    GeneratedComponent[]
  >([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiGenerating, setAiGenerating] = useState(false);

  // Example React component template
  const exampleReactComponent = `import React from 'react';
import styles from './Component.module.scss';

interface ComponentProps {
  title: string;
  subtitle?: string;
  description?: string;
  onAction?: () => void;
}

export const Component: React.FC<ComponentProps> = ({
  title,
  subtitle = "",
  description = "",
  onAction,
}) => {
  return (
    <section className={styles.component}>
      <h1 className={styles.title}>{title}</h1>
      {subtitle && <h2 className={styles.subtitle}>{subtitle}</h2>}
      {description && <p className={styles.description}>{description}</p>}
      {onAction && (
        <button className={styles.button} onClick={onAction}>
          Action
        </button>
      )}
    </section>
  );
};

export default Component;`;

  useEffect(() => {
    // Load example on mount
    if (!sourceCode) {
      setSourceCode(exampleReactComponent);
    }
  }, []);

  const handleConvert = async () => {
    if (!sourceCode.trim()) {
      setError('Please provide source code');
      return;
    }

    setLoading(true);
    setError(null);
    setSuccess(null);

    try {
      // Extract metadata first
      const metadata = extractComponentMetadata(sourceCode);
      const detectedName = metadata.componentName || componentName;

      // Convert component
      const result = convertComponent({
        sourceCode,
        sourceFramework,
        targetFramework,
        componentName: detectedName,
      });

      // Add to generated components
      const generated: GeneratedComponent = {
        code: result.code,
        framework: targetFramework,
        metadata: result.metadata,
        timestamp: Date.now(),
      };

      setGeneratedComponents((prev) => [generated, ...prev]);
      setSuccess(`Component converted to ${targetFramework} successfully!`);
      setTimeout(() => setSuccess(null), 5000);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Conversion failed');
    } finally {
      setLoading(false);
    }
  };

  const handleAIGenerate = async () => {
    if (!aiPrompt.trim()) {
      setError('Please provide a component description');
      return;
    }

    setAiGenerating(true);
    setError(null);
    setSuccess(null);

    try {
      // Call AI API (using free tier LLM)
      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:8080';
      const response = await fetch(`${apiUrl}/api/ai/generate-component`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: aiPrompt,
          framework: sourceFramework,
          componentName,
        }),
      });

      if (!response.ok) {
        throw new Error('AI generation failed');
      }

      const data = await response.json();
      setSourceCode(data.code || data.component);
      setSuccess('Component generated by AI!');
      setTimeout(() => setSuccess(null), 5000);
    } catch (err) {
      // Fallback: Use template-based generation
      console.warn('AI API not available, using template fallback');
      const fallbackCode = generateFromTemplate(aiPrompt, sourceFramework);
      setSourceCode(fallbackCode);
      setSuccess('Component generated from template (AI API unavailable)');
      setTimeout(() => setSuccess(null), 5000);
    } finally {
      setAiGenerating(false);
    }
  };

  const generateFromTemplate = (
    prompt: string,
    framework: SourceFramework
  ): string => {
    // Simple template-based generation
    const lowerPrompt = prompt.toLowerCase();
    const hasButton =
      lowerPrompt.includes('button') || lowerPrompt.includes('cta');
    const hasImage =
      lowerPrompt.includes('image') || lowerPrompt.includes('photo');
    const hasList =
      lowerPrompt.includes('list') || lowerPrompt.includes('items');

    if (framework === 'react') {
      return `import React from 'react';
import styles from './Component.module.scss';

interface ComponentProps {
  title: string;
  ${hasButton ? 'onAction?: () => void;' : ''}
  ${hasImage ? 'imageUrl?: string;' : ''}
  ${hasList ? 'items?: string[];' : ''}
}

export const Component: React.FC<ComponentProps> = ({
  title,
  ${hasButton ? 'onAction,' : ''}
  ${hasImage ? 'imageUrl,' : ''}
  ${hasList ? 'items = [],' : ''}
}) => {
  return (
    <section className={styles.component}>
      <h1 className={styles.title}>{title}</h1>
      ${
        hasImage
          ? '<img src={imageUrl} alt={title} className={styles.image} />'
          : ''
      }
      ${
        hasList
          ? '<ul className={styles.list}>{items.map((item, i) => <li key={i}>{item}</li>)}</ul>'
          : ''
      }
      ${
        hasButton
          ? '<button className={styles.button} onClick={onAction}>Action</button>'
          : ''
      }
    </section>
  );
};

export default Component;`;
    }

    return `// Generated component for ${framework}`;
  };

  const handleCopy = (code: string) => {
    navigator.clipboard.writeText(code);
    setSuccess('Code copied to clipboard!');
    setTimeout(() => setSuccess(null), 3000);
  };

  const handleDownload = (
    code: string,
    framework: TargetFramework,
    name: string
  ) => {
    const extension =
      framework === 'svelte' ? 'svelte' : framework === 'vue' ? 'vue' : 'tsx';
    const filename = `${name}.${extension}`;
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={scssStyles.page}>
      {/* Header */}
      <div className={scssStyles.header}>
        <div>
          <h1 className={scssStyles.headerTitle}>
            <Sparkles className={scssStyles.headerIcon} size={32} />
            AI Component Generator
          </h1>
          <p className={scssStyles.headerSubtitle}>
            Convert components between frameworks or generate new ones with AI
            assistance
          </p>
        </div>
      </div>

      {/* Success/Error Messages */}
      {success && (
        <div className={`${scssStyles.statusMessage} ${scssStyles['statusMessage--success']}`}>
          <CheckCircle2 size={20} />
          <span className={`${scssStyles.statusText} ${scssStyles['statusText--success']}`}>
            {success}
          </span>
        </div>
      )}

      {error && (
        <div className={`${scssStyles.statusMessage} ${scssStyles['statusMessage--error']}`}>
          <AlertCircle size={20} />
          <span className={`${scssStyles.statusText} ${scssStyles['statusText--error']}`}>
            {error}
          </span>
        </div>
      )}

      {/* AI Generation Section */}
      <div className={scssStyles.aiPanel}>
        <h2 className={scssStyles.aiTitle}>
          <Zap className={scssStyles.aiIcon} size={24} />
          AI-Assisted Generation
        </h2>
        <div className={scssStyles.aiForm}>
          <div className={scssStyles.formGroup}>
            <label className={scssStyles.formLabel}>
              Describe your component
            </label>
            <textarea
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
              placeholder="e.g., A hero section with title, subtitle, description, and a call-to-action button"
              className={scssStyles.aiTextarea}
            />
          </div>
          <div className={scssStyles.actionButtons}>
            <select
              value={sourceFramework}
              onChange={(e) =>
                setSourceFramework(e.target.value as SourceFramework)
              }
              className={scssStyles.formSelect}
            >
              <option value="react">React</option>
              <option value="svelte">Svelte</option>
              <option value="vue">Vue</option>
            </select>
            <input
              type="text"
              value={componentName}
              onChange={(e) => setComponentName(e.target.value)}
              placeholder="Component Name"
              className={scssStyles.formInput}
            />
            <button
              onClick={handleAIGenerate}
              disabled={aiGenerating || !aiPrompt.trim()}
              className={scssStyles.aiButton}
            >
              {aiGenerating ? (
                <>
                  <RefreshCw size={18} className={scssStyles.loadingSpinner} />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles size={18} />
                  Generate with AI
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Conversion Section */}
      <div className={scssStyles.generatorGrid}>
        {/* Source Code Editor */}
        <div className={scssStyles.inputPanel}>
          <div className={scssStyles.card}>
            <div className={scssStyles.cardHeader}>
              <h2 className={scssStyles.cardTitle}>
                <FileCode size={20} />
                Source Code
              </h2>
              <select
                value={sourceFramework}
                onChange={(e) =>
                  setSourceFramework(e.target.value as SourceFramework)
                }
                className={scssStyles.formSelect}
              >
                <option value="react">React</option>
                <option value="svelte">Svelte</option>
                <option value="vue">Vue</option>
              </select>
            </div>
            <textarea
              value={sourceCode}
              onChange={(e) => setSourceCode(e.target.value)}
              className={scssStyles.formTextarea}
              spellCheck={false}
            />
            <div className={scssStyles.actionButtons}>
              <button
                onClick={handleConvert}
                disabled={loading || !sourceCode.trim()}
                className={`${scssStyles.button} ${scssStyles['button--primary']}`}
              >
                {loading ? (
                  <>
                    <RefreshCw size={18} className={scssStyles.loadingSpinner} />
                    Converting...
                  </>
                ) : (
                  <>
                    <Code size={18} />
                    Convert
                  </>
                )}
              </button>
              <select
                value={targetFramework}
                onChange={(e) =>
                  setTargetFramework(e.target.value as TargetFramework)
                }
                className={scssStyles.formSelect}
              >
                <option value="svelte">Svelte</option>
                <option value="vue">Vue</option>
                <option value="react">React</option>
                <option value="solidjs">SolidJS</option>
              </select>
            </div>
          </div>
        </div>

        {/* Generated Components */}
        <div className={scssStyles.outputPanel}>
          <div className={scssStyles.card}>
            <h2 className={scssStyles.cardTitle}>
              <Code size={20} />
              Generated Components
            </h2>
            {generatedComponents.length === 0 ? (
              <div className={scssStyles.emptyState}>
                <p className={scssStyles.emptyMessage}>No components generated yet</p>
              </div>
            ) : (
              <div className={scssStyles.generatedList}>
                {generatedComponents.map((comp, idx) => (
                  <div key={idx} className={scssStyles.generatedItem}>
                    <div className={scssStyles.itemHeader}>
                      <div className={scssStyles.itemTitle}>
                        <span>{comp.metadata.componentName}</span>
                        <span className={scssStyles.itemFramework}>
                          ({comp.framework})
                        </span>
                      </div>
                      <div className={scssStyles.itemActions}>
                        <button
                          onClick={() => handleCopy(comp.code)}
                          className={scssStyles.iconButton}
                          title="Copy"
                        >
                          <Copy size={16} />
                        </button>
                        <button
                          onClick={() =>
                            handleDownload(
                              comp.code,
                              comp.framework,
                              comp.metadata.componentName
                            )
                          }
                          className={scssStyles.iconButton}
                          title="Download"
                        >
                          <Download size={16} />
                        </button>
                      </div>
                    </div>
                    <pre className={scssStyles.itemCode}>
                      {comp.code.substring(0, 500)}
                      {comp.code.length > 500 && '...'}
                    </pre>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Info Panel */}
      <div className={scssStyles.infoPanel}>
        <h3 className={scssStyles.infoTitle}>
          <Code size={20} className={scssStyles.infoIcon} />
          How It Works
        </h3>
        <ul className={scssStyles.infoList}>
          <li className={scssStyles.infoItem}>
            <span className={scssStyles.infoBullet}>•</span>
            <span>
              <strong>AI Generation:</strong> Describe your component and let AI
              generate the code
            </span>
          </li>
          <li className={scssStyles.infoItem}>
            <span className={scssStyles.infoBullet}>•</span>
            <span>
              <strong>Framework Conversion:</strong> Convert React components to
              Svelte, Vue, or other frameworks
            </span>
          </li>
          <li className={scssStyles.infoItem}>
            <span className={scssStyles.infoBullet}>•</span>
            <span>
              <strong>Component Registry:</strong> Generated components are
              compatible with the Jxion component registry
            </span>
          </li>
          <li className={scssStyles.infoItem}>
            <span className={scssStyles.infoBullet}>•</span>
            <span>
              <strong>Export & Use:</strong> Download or copy generated code to
              use in your project
            </span>
          </li>
        </ul>
      </div>
    </div>
  );
}
